export const data = [
  {
    id: 1,
    img: '/images/PF-Registration.jpeg',
    title: 'PF Registration',
    link: 'pf-registration',
    category: 'registration',
  },
  {
    id: 2,
    img: '/images/ESIRegistration.jpeg',
    title: 'ESI Registration',
    link: 'esi-registration',
    category: 'registration',
  },
  {
    id: 3,
    img: '/images/dsc.jpeg',
    title: 'DSC (Digital Signature Certification)',
    link: 'dsc',
    category: 'registration',
  },
  {
    id: 4,
    // img: '/images/license.png',
    img: '/logo.svg',
    title: 'License Registration',
    link: 'license-registration',
    category: 'registration',
  },
  {
    id: 5,
    img: '/images/fssai.png',
    title: 'FSSAI (Food License)',
    link: 'fssai',
    category: 'registration',
  },
  {
    id: 6,
    img: '/images/professionalTax.jpeg',
    title: 'Professional Tax Registration',
    link: 'professional-tax-registration',
    category: 'registration',
  },
  {
    id: 7,
    img: '/images/MSME.jpeg',
    title: 'MSME Registration',
    link: 'msme-registration',
    category: 'registration',
  },
  {
    id: 8,
    img: '/images/partners.png',
    title: 'Partnership Registration',
    link: 'partnership-registration',
    category: 'registration',
  },
  {
    id: 9,
    img: '/images/MSME.jpeg',
    title: 'Station8/NGO Registration',
    link: 'ngo-registration',
    category: 'registration',
  },
  {
    id: 10,
    img: '/images/MSME.jpeg',
    title: 'Trust Registration',
    link: 'trust-registration',
    category: 'registration',
  },
  {
    id: 11,
    img: '/images/MSME.jpeg',
    title: 'IE License Partnership',
    link: 'ie-license-partnership',
    category: 'registration',
  },
  {
    id: 12,
    img: '/images/tradeMarkRenewal.png',
    title: 'Trade Mark Renewal',
    link: 'trade-mark-renewal',
    category: 'registration',
  },
  {
    id: 13,
    img: '/images/copyrightRegistration.png',
    title: 'Copy Right Registration',
    link: 'copy-right-registration',
    category: 'registration',
  },
  {
    id: 14,
    img: '/images/iso.png',
    title: 'ISO Registration',
    link: 'iso-registration',
    category: 'registration',
  },
  {
    id: 15,
    // img: '/images/copyrightReply.png',
    img: '/logo.svg',
    title: 'Copyright Reply',
    link: 'copyright-reply',
    category: 'registration',
  },
  {
    id: 16,
    //img: '/images/associationFormation.png',
    img: '/logo.svg',
    title: 'Association Formation',
    link: 'association-formation',
    category: 'registration',
  },
  {
    id: 17,
    //img: '/images/trademarkReply.png',
    img: '/logo.svg',
    title: 'Trademark Reply',
    externalLink: 'https://ipindia.gov.in',
    category: 'registration',
  },
  {
    id: 18,
    //  img: '/images/newsPaperRegistration.png',
    img: '/logo.svg',
    title: 'News Paper Registration',
    link: 'news-paper-registration',
    category: 'registration',
  },
  {
    id: 19,
    img: '/images/gst.jpeg',
    title: 'GST Registration',
    link: 'gst-registration',
    category: 'registration',
  },
  {
    id: 20,
    //img: '/images/shopActRegistration.jpeg',
    img: '/logo.svg',
    title: 'Shop Act Registration',
    link: 'shop-act-registration',
    category: 'registration',
  },
  {
    id: 21,
    //img: '/images/rationCard.jpeg',
    img: '/logo.svg',
    title: 'Ration Card',
    link: 'ration-card',
    category: 'registration',
  },
  {
    id: 22,
    //img: '/images/fireLicenseRegistration.jpeg',
    img: '/logo.svg',
    title: 'Fire License Registration',
    link: 'fire-license-registration',
    category: 'registration',
  },
  {
    id: 23,
    // img: '/images/advertisementAgency.jpeg',
    img: '/logo.svg',
    title: 'Advertisement Agency',
    link: 'advertisement-agency',
    category: 'registration',
  },
  {
    id: 24,
    //img: '/images/nidhiCompany.jpeg',
    img: '/logo.svg',
    title: 'Nidhi Company',
    link: 'nidhi-company',
    category: 'companyRegistration',
  },
  {
    id: 25,
    //img: '/images/companyRegistration.jpeg',
    img: '/logo.svg',
    title: 'Company Registration',
    link: 'companyRegistration',
    category: 'companyRegistration',
  },
  {
    id: 26,
    //img: '/images/TANRegistration.jpeg',
    img: '/logo.svg',
    title: 'TAN Registration',
    link: 'tan-registration',
    category: 'companyRegistration',
  },
  {
    id: 27,
    // img: '/images/corporationLicense.jpeg',
    img: '/logo.svg',
    title: 'Corporation License',
    link: 'corporation-license',
    category: 'companyRegistration',
  },
  {
    id: 28,
    //img: '/images/registeredOfficeChange.jpeg',
    img: '/logo.svg',
    title: 'Registered Office Change',
    link: 'registered-office-change',
    category: 'companyRegistration',
  },
  {
    id: 29,
    //img: '/images/shareAllotment.jpeg',
    img: '/logo.svg',
    title: 'Share Allotment',
    link: 'share-allotment',
    category: 'companyRegistration',
  },
  {
    id: 30,
    //img: '/images/llpRegistration.jpeg',
    img: '/logo.svg',
    title: 'LLP Registration',
    link: 'llp-registration',
    category: 'companyRegistration',
  },
  {
    id: 31,
    //img: '/images/opcRegistration.jpeg',
    img: '/logo.svg',
    title: 'OPC Registration',
    link: 'opc-registration',
    category: 'companyRegistration',
  },
  {
    id: 32,
    //img: '/images/tdsReturnFiling.jpeg',
    title: 'TDS Return Filing',
    link: 'tds-return',
    category: 'returns',
    img: '/logo.svg',
  },
  {
    id: 33,
    //img: '/images/pfMonthlyReturn.jpeg',
    img: '/logo.svg',
    title: 'PF Monthly Return',
    link: 'pf-return',
    category: 'returns',
  },
  {
    id: 34,
    // img: '/images/esiMonthlyReturn.jpeg',
    img: '/logo.svg',
    title: 'ESI Monthly Return',
    link: 'esi-return',
    category: 'returns',
  },
  {
    id: 35,
    //img: '/images/gstReturn.jpeg',
    img: '/logo.svg',
    title: 'GST Return',
    link: 'gst-return',
    category: 'returns',
  },
  {
    id: 36,
    img: '/images/accounting.webp',
    title: 'Accounting',
    link: 'accounting',
    category: 'audits',
  },
  {
    id: 37,
    //img: '/images/audit44AD.png',
    img: '/logo.svg',
    title: 'Audit 44AD',
    link: 'audit-44AD',
    category: 'audits',
  },
  {
    id: 38,
    //img: '/images/audit44ADA.png',
    img: '/logo.svg',
    title: 'Audit 44ADA',
    link: 'audit-44ADA',
    category: 'audits',
  },
  {
    id: 39,
    // img: '/images/audit44AE.png',
    img: '/logo.svg',
    title: 'Audit 44AE',
    link: 'audit-44AAE',
    category: 'audits',
  },
];

export const REGISTER_STARTUP_CATEGORIES = {
  registration: 'Registration',
  companyRegistration: 'Company Registration',
  returns: 'Returns',
  audits: 'Audits',
};
