const gstStateCodes = [
    { code: "01", state: "JAMMU AND KASHMIR" },
    { code: "02", state: "HIMACHAL PRADESH" },
    { code: "03", state: "PUNJAB" },
    { code: "04", state: "CHANDIGARH" },
    { code: "05", state: "UTTARAKHAND" },
    { code: "06", state: "HARYANA" },
    { code: "07", state: "DELHI" },
    { code: "08", state: "RAJASTHAN" },
    { code: "09", state: "UTTAR PRADESH" },
    { code: "10", state: "BIHAR" },
    { code: "11", state: "SIKKIM" },
    { code: "12", state: "ARUNACHAL PRADESH" },
    { code: "13", state: "NAGALAND" },
    { code: "14", state: "MANIPUR" },
    { code: "15", state: "MIZORAM" },
    { code: "16", state: "TRIPURA" },
    { code: "17", state: "MEGHALAYA" },
    { code: "18", state: "ASSAM" },
    { code: "19", state: "WEST BENGAL" },
    { code: "20", state: "JHARKHAND" },
    { code: "21", state: "ODISHA" },
    { code: "22", state: "CHATTISGARH" },
    { code: "23", state: "MADHYA PRADESH" },
    { code: "24", state: "GUJARAT" },
    { code: "26", state: "DADRA AND NAGAR HAVELI AND DAMAN AND DIU (NEWLY MERGED UT)" },
    { code: "27", state: "MAHARASHTRA" },
    { code: "28", state: "ANDHRA PRADESH(BEFORE DIVISION)" },
    { code: "29", state: "KARNATAKA" },
    { code: "30", state: "GOA" },
    { code: "31", state: "LAKSHADWEEP" },
    { code: "32", state: "KERALA" },
    { code: "33", state: "TAMIL NADU" },
    { code: "34", state: "PUDUCHERRY" },
    { code: "35", state: "ANDAMAN AND NICOBAR ISLANDS" },
    { code: "36", state: "TELANGANA" },
    { code: "37", state: "ANDHRA PRADESH (NEWLY ADDED)" },
    { code: "38", state: "LADAKH (NEWLY ADDED)" },
    { code: "97", state: "OTHER TERRITORY" },
    { code: "99", state: "CENTRE JURISDICTION" }
];
export default gstStateCodes