export const itr1 = {
    Form_ITR1: {
        FormName: "ITR-1",
        Description:
            "For Indls having Income from Salary, Pension, family pension and Interest",
        AssessmentYear: "2022",
        SchemaVer: "Ver1.0",
        FormVer: "Ver1.0",
    },
    PersonalInfo: {
        AssesseeName: {
            FirstName: "",
            MiddleName: "",
            SurNameOrOrgName: "",
        },
        PAN: "",
        Address: {
            ResidenceNo: "",
            ResidenceName: "",
            RoadOrStreet: "",
            LocalityOrArea: "",
            CityOrTownOrDistrict: "",
            StateCode: 0,
            CountryCode: 0,
            PinCode: 0,
            CountryCodeMobile: 0,
            MobileNo: 0,
            EmailAddress: "",
        },
        DOB: "",
        EmployerCategory: "",
        AadhaarCardNo: 0,
    },
    FilingStatus: {
        ReturnFileSec: 0,
        NewTaxRegime: "O",
        SeventhProvisio139: "139(1)",
    },
    ITR1_IncomeDeductions: {
        GrossSalary: 0,
        Salary: 0,
        PerquisitesValue: 0,
        ProfitsInSalary: 0,
        AllwncExemptUs10: {
            TotalAllwncExemptUs10: 0,
        },
        NetSalary: 0,
        DeductionUs16: 0,
        DeductionUs16ia: 0,
        EntertainmentAlw16ii: 0,
        ProfessionalTaxUs16iii: 0,
        IncomeFromSal: 0,
        GrossRentReceived: 0,
        TaxPaidlocalAuth: 0,
        AnnualValue: 0,
        StandardDeduction: 0.3,
        InterestPayable: 0,
        ArrearsUnrealizedRentRcvd: 0,
        TotalIncomeOfHP: 0,
        IncomeOthSrc: 0,
        OthersInc: {
            OthersIncDtlsOthSrc: [
                {
                    OthSrcNatureDesc: "OTH",
                    OthSrcOthNatOfInc: "Other Item",
                    OthSrcOthAmount: 0,
                },
            ],
        },
        DeductionUs57iia: 0,
        GrossTotIncome: 0,
        UsrDeductUndChapVIA: {
            Section80C: 0,
            Section80CCC: 0,
            Section80CCDEmployeeOrSE: 0,
            Section80CCD1B: 0,
            Section80CCDEmployer: 0,
            Section80D: 0,
            Section80DD: 0,
            Section80DDB: 0,
            Section80E: 0,
            Section80EE: 0,
            Section80EEA: 0,
            Section80EEB: 0,
            Section80G: 0,
            Section80GG: 0,
            Section80GGA: 0,
            Section80GGC: 0,
            Section80U: 0,
            Section80TTA: 0,
            Section80TTB: 0,
            TotalChapVIADeductions: 0,
        },
        DeductUndChapVIA: {
            Section80C: 0,
            Section80CCC: 0,
            Section80CCDEmployeeOrSE: 0,
            Section80CCD1B: 0,
            Section80CCDEmployer: 0,
            Section80D: 0,
            Section80DD: 0,
            Section80DDB: 0,
            Section80E: 0,
            Section80EE: 0,
            Section80EEA: 0,
            Section80EEB: 0,
            Section80G: 0,
            Section80GG: 0,
            Section80GGA: 0,
            Section80GGC: 0,
            Section80U: 0,
            Section80TTA: 0,
            Section80TTB: 0,
            TotalChapVIADeductions: 0,
        },
        TotalIncome: 0,
        ExemptIncAgriOthUs10: { ExemptIncAgriOthUs10Total: 0 },
        IncomeNotified89A: 0,
        IncomeNotifiedOther89A: 0,
        Increliefus89A: 0,
        Increliefus89AOS: 0,
    },
    ITR1_TaxComputation: {
        TotalTaxPayable: 0,
        Rebate87A: 0,
        TaxPayableOnRebate: 0,
        EducationCess: 0.4,
        GrossTaxLiability: 0,
        Section89: 0,
        NetTaxLiability: 0,
        TotalIntrstPay: 0,
        IntrstPay: {
            IntrstPayUs234A: 0,
            IntrstPayUs234B: 0,
            IntrstPayUs234C: 0,
            LateFilingFee234F: 0,
        },
        TotTaxPlusIntrstPay: 0,
    },
    TaxPaid: {
        TaxesPaid: {
            AdvanceTax: 0,
            TDS: 0,
            TCS: 0,
            SelfAssessmentTax: 0,
            TotalTaxesPaid: 0,
        },
        BalTaxPayable: 0,
    },
    Refund: {
        RefundDue: 0,
        BankAccountDtls: {
            AddtnlBankDetails: 0,
        },
    },
    Schedule80G: {
        TotalDonationsUs80GCash: 0,
        TotalDonationsUs80GOtherMode: 0,
        TotalDonationsUs80G: 0,
        TotalEligibleDonationsUs80G: 0,
    },
    Schedule80D: {
        Sec80DSelfFamSrCtznHealth: {
            SeniorCitizenFlag: "S",
            SelfAndFamily: 0,
            HealthInsPremSlfFam: 0,
            PrevHlthChckUpSlfFam: 0,
            SelfAndFamilySeniorCitizen: 0,
            HlthInsPremSlfFamSrCtzn: 0,
            PrevHlthChckUpSlfFamSrCtzn: 0,
            MedicalExpSlfFamSrCtzn: 0,

            ParentsSeniorCitizenFlag: "P",
            Parents: 0,
            HlthInsPremParents: 0,
            PrevHlthChckUpParents: 0,
            ParentsSeniorCitizen: 0,
            HlthInsPremParentsSrCtzn: 0,
            PrevHlthChckUpParentsSrCtzn: 0,
            MedicalExpParentsSrCtzn: 0,
            EligibleAmountOfDedn: 0,
        },
    },
    TDSonOthThanSals: {
        TotalTDSonOthThanSals: 0,
    },
    ScheduleTDS3Dtls: { TotalTDS3Details: 0 },
    ScheduleTCS: { TotalSchTCS: 0 },
    Verification: {
        Declaration: {
            AssesseeVerName: 0,
            FatherName: 0,
            AssesseeVerPAN: 0,
        },
        Capacity: "S",
        Place: 0,
    },
};
