const InputStyles = {
    label:`
        block 
        uppercase
        tracking-wide
        text-gray-700
        text-xs
        font-bold
        mb-2
    `,
    input:`
        bg-gray-100
        appearance-none 
        border
        border-gray-300 
        rounded 
        w-full
        py-1
        px-2
        text-gray-700 
        leading-tight 
        focus:outline-none 
        focus:bg-white 
        focus:border-primary
    `,
    error_border:`
        text-red-600
        border-red-600
        focus:border-red-600
    `,
    error_msg:`
        text-red-500
        text-xs
        italic
    `,
    selectInput:`
        block 
        //appearance-none 
        w-full 
        bg-gray-100 
        border 
        border-gray-300 
        text-gray-700
        py-1
        px-4 
        pr-8 
        rounded 
        leading-tight 
        focus:outline-none 
        focus:bg-white 
        focus:border-primary
    `,
    tempInput:`
        appearance-none 
        border
        border-gray-300 
        dark:border-neutral-500 
        rounded 
        w-full
        xl:py-3
        py-2
        px-2

        bg-gray-100
        text-gray-700 
        dark:bg-neutral-700 
        dark:text-neutral-100 

        leading-tight 
        focus:outline-none 
        focus:bg-white 
        focus:border-primary
        dark:focus:border-primary
    `,
    tempSelect:`
        bg-neutral-100
		border
		border-neutral-300
		text-neutral-900
		text-sm
		rounded-lg
		focus:ring-blue-500
		focus:border-blue-500
		block
		w-full
		p-2.5
		dark:bg-neutral-700
		dark:border-neutral-600
		dark:placeholder-neutral-400
		dark:text-white
		dark:focus:ring-blue-500
		dark:focus:border-blue-500
    `

}
export {InputStyles}

