const Tnc = () => {
  return (
    <>
      
      <div
        className="bg-blue-500  "
        style={{ paddingBottom: "5rem", paddingTop: "5rem" }}
      >
        <div className="  container mx-auto">
          <div className="row">
            <div className="">
              
              <h2
                className="text-center text-[3rem] text-white"
                // style={{
                //   fontSize: "3rem",
                //   textShadow: "0 4px 6px rgb(0 0 0 / 50%)",
                // }}
              >
                <b>Terms & Conditions</b>
              </h2>
              <h6 className="text-white text-center">– FOR ITAX EASY</h6>
            </div>
            <div className=" text-center">
              {/* <button className=" text-white bg-blue-900 px-3 py-2 mt-1 rounded-lg  shadow-2xl hover:bg-black-100">
                {" "}
                Get Started
              </button> */}
              <h6 className="text-white my-3">
                Get access to customer-only benefits
              </h6>
            </div>
          </div>
        </div>
      </div>
      <div className="container mx-auto">
        <div className="text-justify">
          <div className="containerFFF mx-auto text-serif mt-5 my-20 py-20 bg-gray-100 rounded-lg shadow-lg px-10">
            <div className="border-l-2 px-4 border-l-blue-500 py-4 my-6 bg-blue-100">
              <h5 className="tctext">
                {" "}
                Our Association With You Is Our Most Important Asset. We Want
                You To Feel Comfortable And Confident When Using Our Platform
                (defined Hereinafter) And The Services (defined Hereinafter).
                The Objectives Of These Terms And Conditions Of Use (&quot;
                terms&quot;) Are To Inform You Of The Terms Which Apply To Your
                Access To The Platform And Services, What We Expect From You,
                And What You Can Expect From Us As You Use And Interact With Our
                Platform And The Services Provided By Us, Our Strategic Partners
                And Third Party Service Providers.
              </h5>
            </div>{" "}
            <h5 className="tctext">
              The Platform Is Provided By Itax Easy Private Limited (shall Be
              Herein After Referred To As Itax Easy) , A Company Incorporated On
              24 Dec 2019 Under The Companies Act 2013, Having Its Registered
              Office At G 41, Gandhi Nagar, Padav, Gwalior Madhya Pradesh 474002
              - And Its Corporate Office At Flat No 811 Sat 1 Sector 143 Noida
              201306 Uttar Pradesh. user And Company Are Each A
              &quot;party&quot; And Collectively The &quot;parties&quot;.
            </h5>
            <h5 className="tctext">
              these Terms Are An Electronic Record In Terms Of The (indian)
              Information Technology Act, 2000 And Rules Thereunder As
              Applicable And As Amended From Time To Time (&quot;it Act&quot;).
              This Electronic Record Is Generated By A Computer System And Does
              Not Require Any Physical Or Digital Signatures. These Terms Are
              Published In Accordance With The Provisions Of Rule 3(1)(a) Of The
              Information Technology (intermediary Guidelines And Digital Media
              Ethics Code) Rules, 2021 Framed Under The It Act (as Amended From
              Time To Time), That Require Publishing The Terms Of Services And
              Practices For Access Or Usage Of Platform And Services. These
              Terms Constitute A Binding And Legally Enforceable Contract
              Between The Company And User (as Defined Below). <br />
              <br />
              by Registering On Or Using The Platform Or Availing The Services,
              You Agree To Be Bound By The Terms. If You Are Using The Platform
              On Behalf Of An Organization, You Are Agreeing To The Terms On
              Behalf Of That Organization (in Which Event, &quot;you&quot;,
              &quot;your&quot; Or &quot;user&quot; Will Refer To That
              Organization).
              <br />
              <br />
              you Represent That You Have Not Been Previously Suspended Or
              Removed By The Company, Or Disqualified For Any Other Reason, From
              Availing The Services Or Using The Platform. In Addition, You
              Represent And Warrant That You Have The Right, Authority And
              Capacity To Agree To The Terms And To Abide By Them. You Shall Not
              Impersonate Any Person Or Entity, Or Falsely State Or Otherwise
              Misrepresent Your Identity, Age Or Affiliation With Any Person Or
              Entity. In The Event Of Any Violation Of The Terms, The Company
              Reserves The Right To Suspend Or Permanently Prevent You From
              Availing The Services Or Using The Platform.
              <br />
              <br />
              if You Do Not Agree To Be Bound By These Terms, You Must Not Use
              The Platform. By Continuing To Use The Platform Or The Services
              You Expressly Agree And Undertake To Be Bound By These Terms.
              Subject To Applicable Laws, These Terms (and Any Changes Thereto)
              Will Become Applicable To You Retrospectively On And From The Date
              Of Your First Use Of The Platform. By Visiting Our Website And
              Accessing The Information, Resources, Services, Products, And
              Tools We Provide, You Understand And Agree To Accept And Adhere To
              The Following Terms And Conditions As Stated In This Policy
              (hereafter Referred To As &apos;user Agreement&apos;), Along With
              The Terms And Conditions As Stated In Our Privacy Policy (please
              Refer To The Privacy Policy Section Below For More Information).
              <br />
              <br />
              We Reserve The Right To Change This User Agreement From Time To
              Time Without Notice. You Acknowledge And Agree That It Is Your
              Responsibility To Review This User Agreement Periodically To
              Familiarize Yourself With Any Modifications. Your Continued Use Of
              This Site After Such Modifications Will Constitute Acknowledgment
              And Agreement Of The Modified Terms And Conditions.
              <br />
            </h5>
          </div>
          <div className="container mx-auto text-serif my-20 py-20 bg-gray-100 rounded-lg shadow-lg px-10">
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              1. Responsible Use And Conduct
            </h2>
            <ul>
              <li className="tcli">
                In Order To Access Our Resources, You May Be Required To Provide
                Certain Information About Yourself (such As Identification,
                Email, Phone Number, Contact Details, Etc.) As Part Of The
                Registration Process, Or As Part Of Your Ability To Use The
                Resources. You Agree That Any Information You Provide Will
                Always Be Accurate, Correct, And Up To Date..
              </li>
              <li className="tcli">
                You Are Responsible For Maintaining The Confidentiality Of Any
                Login Information Associated With Any Account You Use To Access
                Our Resources. Accordingly, You Are Responsible For All
                Activities That Occur Under Your Accounts.
              </li>
              <li className="tcli">
                Accessing ( (or Attempting To Access) Any Of Our Resources By
                Any Means Other Than Through The Means We Provide, Is Strictly
                Prohibited. You Specifically Agree Not To Access (or Attempt To
                Access) Any Of Our Resources Through Any Automated, Unethical Or
                Unconventional Means.
              </li>
              <li className="tcli">
                Engaging In Any Activity That Disrupts Or Interferes With Our
                Resources, Including The Servers And/or Networks To Which Our
                Resources Are Located Or Connected, Is Strictly Prohibited.
              </li>
              <li className="tcli">
                Attempting To Copy, Duplicate, Reproduce, Sell, Trade, Or Resell
                Our Resources Is Strictly Prohibited.
              </li>
              <li className="tcli">
                You Are Solely Responsible Any Consequences, Losses, Or Damages
                That We May Directly Or Indirectly Incur Or Suffer Due To Any
                Unauthorized Activities Conducted By You, As Explained Above,
                And May Incur Criminal Or Civil Liability.
              </li>
              <div className="border-l-2 px-4 border-l-blue-500 py-4 my-6 bg-blue-100">
                <li className="tcli">
                  We May Provide Various Open Communication Tools On Our
                  Website, Such As Blog Comments, Blog Posts, Public Chat,
                  Forums, Message Boards, Newsgroups, Product Ratings And
                  Reviews, Various Social Media Services, Etc. You Understand
                  That Generally We Do Not Pre-screen Or Monitor The Content
                  Posted By Users Of These Various Communication Tools, Which
                  Means That If You Choose To Use These Tools To Submit Any Type
                  Of Content To Our Website, Then It Is Your Personal
                  Responsibility To Use These Tools In A Responsible And Ethical
                  Manner. By Posting Information Or Otherwise Using Any Open
                  Communication Tools As Mentioned, You Agree That You Will Not
                  Upload, Post, Share, Or Otherwise Distribute Any Content That:
                </li>

                <li className="tcli">
                  Is Illegal, Threatening, Defamatory, Abusive, Harassing,
                  Degrading, Intimidating, Fraudulent, Deceptive, Invasive,
                  Racist, Or Contains Any Type Of Suggestive, Inappropriate, Or
                  Explicit Language;
                </li>
                <li className="tcli">
                  Infringes On Any Trademark, Patent, Trade Secret, Copyright,
                  Or Other Proprietary Right Of Any Party;
                </li>
                <li className="tcli">
                  Contains Any Type Of Unauthorized Or Unsolicited Advertising;
                </li>
                <li className="tcli">
                  Impersonates Any Person Or Entity, Including Any
                  Www.itaxeasy.com Employees Or Representatives.
                </li>
              </div>
            </ul>
            <h5 className="tctext">
              We Have The Right At Our Sole Discretion To Remove Any Content
              That, We Feel In Our Judgment Does Not Comply With This User
              Agreement, Along With Any Content That We Feel Is Otherwise
              Offensive, Harmful, Objectionable, Inaccurate, Or Violates Any
              Third Party Copyrights Or Trademarks. We Are Not Responsible For
              Any Delay Or Failure In Removing Such Content. If You Post Content
              That We Choose To Remove, You Hereby Consent To Such Removal, And
              Consent To Waive Any Claim Against Us.
            </h5>
            <ul>
              <li className="tcli">
                We Do Not Assume Any Liability For Any Content Posted By You Or
                Any Other Third Party Users Of Our Website. However, Any Content
                Posted By You Using Any Open Communication Tools On Our Website,
                Provided That It Doesn&apos;t Violate Or Infringe On Any Third
                Party Copyrights Or Trademarks, Becomes The Property Of
                Www.itaxeasy.com, And As Such, Gives Us A Perpetual,
                Irrevocable, Worldwide, Royalty-free, Exclusive License To
                Reproduce, Modify, Adapt, Translate, Publish, Publicly Display
                And/or Distribute As We See Fit. This Only Refers And Applies To
                Content Posted Via Open Communication Tools As Described, And
                Does Not Refer To Information That Is Provided As Part Of The
                Registration Process, Necessary In Order To Use Our Resources.
                All Information Provided As Part Of Our Registration Process Is
                Covered By Our Privacy Policy.
              </li>
              <li className="tcli">
                You Agree To Indemnify And Hold Harmless Itaxeasy A Digital
                Property Of Itaxeasy Private Limited And Its Parent Company And
                Affiliates, And Their Directors, Officers, Managers, Employees,
                Donors, Agents, And Licensors, From And Against All Losses,
                Expenses, Damages And Costs, Including Reasonable
                Attorneys&apos; Fees, Resulting From Any Violation Of This User
                Agreement Or The Failure To Fulfil Any Obligations Relating To
                Your Account Incurred By You Or Any Other Person Using Your
                Account. We Reserve The Right To Take Over The Exclusive Defense
                Of Any Claim For Which We Are Entitled To Indemnification Under
                This User Agreement. In Such Event, You Shall Provide Us With
                Such Cooperation As Is Reasonably Requested By Us.
              </li>
            </ul>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              2. Privacy
            </h2>
            <h5 className="tctext">
              Your Privacy Is Very Important To Us, Which Is Why We&apos;ve
              Created A Separate Privacy Policy In Order To Explain In Detail
              How We Collect, Manage, Process, Secure, And Store Your Private
              Information. Our Privacy Policy Is Included Under The Scope Of
              This User Agreement. To Read Our Privacy Policy In Its Entirety,
              Click Here.
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              3. Limitation Of Warranties
            </h2>
            <h5 className="tctext">
              By Using Our Website, You Understand And Agree That All Resources
              We Provide Are &quot;as Is&quot; And &quot;as Available&quot;.
              This Means That We Do Not Represent Or Warrant To You That:
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              4. Limitation Of Liability
            </h2>
            <h5 className="tctext">
              In Conjunction With The Limitation Of Warranties As Explained
              Above, You Expressly Understand And Agree That Any Claim Against
              Us Shall Be Limited To The Amount You Paid, If Any, For Use Of
              Products And/or Services. Www.itaxeasy.com Will Not Be Liable For
              Any Direct, Indirect, Incidental, Consequential Or Exemplary Loss
              Or Damages Which May Be Incurred By You As A Result Of Using Our
              Resources, Or As A Result Of Any Changes, Data Loss Or Corruption,
              Cancellation, Loss Of Access, Or Downtime To The Full Extent That
              Applicable Limitation Of Liability Laws Apply.
            </h5>

            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              5. Copyrights / Trademarks
            </h2>
            <h5 className="tctext">
              All Content And Materials Available On Www.itaxeasy.com, Including
              But Not Limited To Text, Graphics, Website Name, Code, Images And
              Logos Are The Intellectual Property Of Itaxeasy Private Limited,
              And Are Protected By Applicable Copyright And Trademark Law. Any
              Inappropriate Use, Including But Not Limited To The Reproduction,
              Distribution, Display Or Transmission Of Any Content On This Site
              Is Strictly Prohibited, Unless Specifically Authorized By The
              Company.
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              6. Termination Of Use
            </h2>
            <h5 className="tctext">
              You Agree That We May, At Our Sole Discretion, Suspend Or
              Terminate Your Access To All Or Part Of Our Website And Resources
              With Or Without Notice And For Any Reason, Including, Without
              Limitation, Breach Of This User Agreement. Any Suspected Illegal,
              Fraudulent Or Abusive Activity May Be Grounds For Terminating Your
              Relationship And May Be Referred To Appropriate Law Enforcement
              Authorities. Upon Suspension Or Termination, Your Right To Use The
              Resources We Provide Will Immediately Cease, And We Reserve The
              Right To Remove Or Delete Any Information That You May Have On
              File With Us, Including Any Account Or Login Information.
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              7. Governing Law
            </h2>
            <h5 className="tctext">
              This Website Is Controlled By Itaxeasy Private Limited From Our
              Offices Located In The State Of Delhi, India. It Can Be Accessed
              By Most Countries Around The World. &quot;all Disputes Arising Out
              Of Or In Connection With The Present Contract Shall Be Submitted
              To The Madhya Pradesh Arbitration Tribunal And Shall Be Finally
              Settled In Accordance With Arbitration Act And Rules By Appointing
              One Or More Arbitrators In Accordance With The Said Rules.&quot;
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              8. Cancellation And Refund
            </h2>
            <h5 className="tctext">
              Cancellation Of Order Is Not Possible Once The Payment Has Been
              Made. No Refunds Will Be Given Except In The Event Of Cancellation
              Or Non-performance Of Service By ITAXEASY Private Limited.
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              9. Guarantee
            </h2>
            <h5 className="tctext">
              Unless Otherwise Expressed, Www.itaxeasy.com.com Expressly
              Disclaims All Warranties And Conditions Of Any Kind, Whether
              Express Or Implied, Including, But Not Limited To The Implied
              Warranties And Conditions Of Merchantability, Fitness For A
              Particular Purpose And Non-infringement.
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              10. Contact Information
            </h2>
            <h5 className="tctext">
              If You Have Any Questions Or Comments About These Our Terms Of
              Service As Outlined Above, You Can Mail Us At: <br />
              support@itaxeasy.com
            </h5>
            <h2 className="text-lg font-italic  font-semibold mt-5   pb-2">
              Change to Refund & Cancellation Policy
            </h2>
            <h5 className="tctext">
              At ITAXEASY , We Take Pride In The Services Delivered By Us And
              Guarantee Your Satisfaction With Our Services And Support. We
              Constantly Improve And Strive To Deliver The Best Accounting,
              Financial Or Secretarial Services Through The Internet. However,
              In Case You Are Not Satisfied With Our Services, Please Contact Us
              Immediately And We Will Correct The Situation, Provide A Refund Or
              Offer Credit That Can Be Used For Future ITAXEASY Orders.
            </h5>
          </div>

          <div className="container mx-auto text-serif mt-5 my-20 py-20 bg-gray-100 rounded-lg shadow-lg px-10">
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              Refund Policy
            </h2>
            <h5 className="tctext">
              When A Payment Of Fee Is Made To Itaxeasy , The Fees Paid In
              Advance Is Retained By Itaxeasy In A Client Account. Itaxeasy Will
              Earn The Fees Upon Working On A Client&apos;s Matter. During An
              Engagement, Itaxeasy Earns Fee At Different Rates And Different
              Times Depending On The Completion Of Various Milestones (e.g.
              Providing Client Portal Access, Assigning Relationship Manager,
              Obtaining Din, Filing Of Forms, Etc.,). Refund Cannot Be Provided
              For Earned Fee Because Resources And Man Hours Spent On Delivering
              The Service Are Non-returnable In Nature. Further, We Can&apos;t
              Refund Or Credit Any Money Paid To Government Entities, Such As
              Filing Fees Or Taxes, Or To Other Third Parties With A Role In
              Processing Your Order. Under Any Circumstance, Itaxeasy Shall Be
              Liable To Refund Only Upto The Fee Paid By The Client.
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              Procedure for Requesting Refund
            </h2>
            <h5 className="tctext">
              Refund Request Can Be Initiated Through our Refund Platform After
              Signing In. To Request A Refund, Please Request A Refund In The
              Concerned Chat Room To The Relevant Engagement Manager. All Refund
              Requests Must Be Made Within 60 Days Of Purchase. Refund Request
              Over 60 Days Will Not Be Accepted And Only Credit Will Be Provided
              For Completion Of Service / Change Of Service. We Will Complete
              Processing Your Refund Request Within 4 To 5 Weeks Of Receiving
              All The Information Required For Processing Refund Like Reason For
              Refund, Bank Details For Processing Request, Etc.
            </h5>
            <h2 className="text-lg font-italic  font-semibold mt-5   pb-2">
              Change of Service
            </h2>
            <h5 className="tctext">
              If You Want To Change The Service You Ordered For A Different One,
              You Must Request This Change Of Service Within 60 Days Of
              Purchase. The Purchase Price Of The Original Service, Less Any
              Earned Fee And Money Paid To Government Entities, Such As Filing
              Fees Or Taxes, Or To Other Third Parties With A Role In Processing
              Your Order, Will Be Credited To Your Itaxeasy Account. You Can Use
              The Balance Credit For Any Other ITAXEASY Service.
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              Standard Pricing
            </h2>
            <h5 className="tctext">
              ITAXEASY Has A Standard Pricing Policy Wherein No Additional
              Service Fee Is Requested Under Any Circumstance. However, The
              Standard Pricing Policy Is Not Applicable For An Increase In The
              Total Fee Paid By The Client To Itaxeasy Due To Increase In
              Government Fee Or Fee Incurred By The Client For Completion Of
              Legal Documentation Or Re-filing Of Forms With The Government Due
              To Rejection Or Resubmission. Itaxeasy Is Not Responsible Or
              Liable For Any Other Cost Incurred By The Client Related To The
              Completion Of The Service.
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              Factors Outside Our Control
            </h2>
            <h5 className="tctext">
              We Cannot Guarantee The Results Or Outcome Of Your Particular
              Procedure. For Instance, The Government May Reject A Trademark
              Application For Legal Reasons Beyond The Scope Of Itaxeasy
              Service. In Some Cases, A Government Backlog Or Problems With The
              Government Platforms (e.g. Mca Website, Income Tax Website, Fssai
              Website) Can Lead To Long Delays Before Your Process Is Complete.
              Similarly, Itaxeasy Does Not Guarantee The Results Or Outcomes Of
              The Services Rendered By Our Associates On Nearest.expert
              Platform, Who Are Not Employed By Itaxeasy . Problems Like These
              Are Beyond Our Control And Are Not Covered By This Guarantee Or
              Eligible For Refund. Hence, Delay In Processing Of Your File By
              The Government Cannot Be A Reason For Refund.
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              Force Majeure
            </h2>
            <h5 className="tctext">
              ITAXEASY Shall Not Be Considered In Breach Of Its Satisfaction
              Guarantee Policy Or Default Under Any Terms Of Service, And Shall
              Not Be Liable To The Client For Any Cessation, Interruption, Or
              Delay In The Performance Of Its Obligations By Reason Of
              Earthquake, Flood, Fire, Storm, Lightning, Drought, Landslide,
              Hurricane, Cyclone, Typhoon, Tornado, Natural Disaster, Act Of God
              Or The Public Enemy, Epidemic, Famine Or Plague, Action Of A Court
              Or Public Authority, Change In Law, Explosion, War, Terrorism,
              Armed Conflict, Labor Strike, Lockout, Boycott Or Similar Event
              Beyond Our Reasonable Control, Whether Foreseen Or Unforeseen
              (each A &quot;force Majeure Event&quot;).
            </h5>
            <h2 className="text-lg font-italic  font-semibold  mt-5   pb-2">
              Cancellation Fee
            </h2>
            <h5 className="tctext">
              Since We&apos;re Incurring Costs And Dedicating Time, Manpower,
              Technology Resources And Effort To Your Service Or Document
              Preparation, Our Guarantee Only Covers Satisfaction Issues Caused
              By Itaxeasy - Not Changes To Your Situation Or Your State Of Mind.
              In Case You Require Us To Hold The Processing Of A Service, We
              Will Hold The Fee Paid On Your Account Until You Are Ready To
              Commence The Service.
            </h5>
            <h5 className="tctext">
              Before Processing Any Refund, We Reserve The Right To Make Best
              Effort To Complete The Service. In Case, You Are Not Satisfied
              With The Service, A Cancellation Fee Of 20% + Earned Fee + Fee
              Paid To Government Would Be Applicable. In Case Of Change Of
              Service, The Cancellation Fee Would Not Be Applicable.
            </h5>
          </div>
        </div>
      </div>
    </>
  );
};

export default Tnc;
